
import React, { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import axios from "axios";
import { Navbar, Nav, NavDropdown, Container, Row, Col } from "react-bootstrap";

import { getExpectedExpenses } from "../../Services/AIService";
import { getCropById } from "../../Services/CropService";
import { getFarmById } from "../../Services/FarmService";
import { logoutUser } from "../../Services/LoginService";

import "../../DisplayView.css";

import {
    FaMoneyBillWave,
    FaSeedling,
    FaLeaf,
    FaGlobeAmericas,
    FaVectorSquare,
    FaCalendarAlt,
    FaChartLine,
    FaWater,
    FaFlask,
    FaShieldAlt,
    FaTractor,
    FaTools,
    FaArrowLeft
} from "react-icons/fa";

const FarmCropExpense = () => {
    const navigate = useNavigate();
    const { cid } = useParams();

    const [report, setReport] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");

    useEffect(() => {
        const loadExpenseReport = async () => {
            try {
                if (!cid) {
                    throw new Error("Crop ID is missing.");
                }

                setLoading(true);
                setError("");

                console.log("Selected Crop ID:", cid);

                // =====================================================
                // 1. GET CROP DETAILS
                // =====================================================

                const cropResponse = await getCropById(cid);
                const crop = cropResponse.data;

                console.log("Crop Details:", crop);

                if (!crop) {
                    throw new Error("Crop details not found.");
                }

                // =====================================================
                // 2. GET FARM DETAILS
                // =====================================================

                const farmId =
                    crop.farmId ??
                    crop.farmID ??
                    crop.farm?.farmId ??
                    crop.farm?.id;

                let farm = null;

                if (farmId) {
                    const farmResponse = await getFarmById(farmId);
                    farm = farmResponse.data;

                    console.log("Farm Details:", farm);
                }

                // =====================================================
                // 3. GET RESOURCE QUANTITIES
                // =====================================================
                // AI is used ONLY for predicting required quantities.
                // AI rates are NOT used for expense calculation.

                const aiResponse = await getExpectedExpenses(cid);
                const ai = aiResponse.data;

                console.log("Predicted Resource Quantities:", ai);

                if (!ai) {
                    throw new Error(
                        "No resource prediction data received."
                    );
                }

                // =====================================================
                // 4. GET SAVED EXPENSE RATES
                // =====================================================
                // These values come from the database.
                // They are NOT generated by AI.

                const expenseResponse = await axios.get(
                    "http://localhost:9696/farmverse/agroexpense",
                    { withCredentials: true }
                );

                const expenseItems = expenseResponse.data;

                console.log(
                    "Saved Agro Expense Rates:",
                    expenseItems
                );

                if (
                    !Array.isArray(expenseItems) ||
                    expenseItems.length === 0
                ) {
                    throw new Error(
                        "No saved agro expense rates found in database."
                    );
                }

                // =====================================================
                // 5. GET RESOURCE QUANTITIES
                // =====================================================

                const water = Number(
                    ai.water ??
                    ai.waterGallon ??
                    0
                );

                const fertilizer = Number(
                    ai.fertilizer ?? 0
                );

                const pesticides = Number(
                    ai.pesticides ??
                    ai.pesticide ??
                    0
                );

                const tractorHour = Number(
    ai.tractorHour ?? 0
);

const agroTools = Number(
    ai.agroTools ??
    ai.agroTool ??
    ai.agroToolsRequired ??
    crop.cropArea ??
    0
);

                console.log("Resource Quantities:", {
                    water,
                    fertilizer,
                    pesticides,
                    tractorHour,
                    agroTools
                });

                // =====================================================
                // 6. FIND SAVED DATABASE RATE
                // =====================================================

                const getRate = (expenseName) => {
                    const expense = expenseItems.find((item) => {
                        const savedName = String(
                            item.expenseName ?? ""
                        )
                            .trim()
                            .toLowerCase();

                        return savedName ===
                            expenseName.trim().toLowerCase();
                    });

                    if (!expense) {
                        throw new Error(
                            `Saved rate not found for ${expenseName}.`
                        );
                    }

                    const rate = Number(
                        expense.ratePerUnit ?? 0
                    );

                    if (Number.isNaN(rate)) {
                        throw new Error(
                            `Invalid saved rate for ${expenseName}.`
                        );
                    }

                    return rate;
                };

                // =====================================================
                // 7. GET SAVED MENTOR RATES
                // =====================================================

                const waterRate =
                    getRate("waterGallon");

                const fertilizerRate =
                    getRate("fertilizer");

                const pesticidesRate =
                    getRate("pesticides");

                const tractorRate =
                    getRate("tractorHour");

                const agroToolsRate =
                    getRate("agroTools");

                console.log("DATABASE RATES:", {
                    waterRate,
                    fertilizerRate,
                    pesticidesRate,
                    tractorRate,
                    agroToolsRate
                });

                // =====================================================
                // 8. CALCULATE EXPENSE
                // =====================================================
                // Quantity = predicted resource requirement
                // Rate     = saved database/mentor rate

                const waterExp =
                    water * waterRate;

                const fertilizerExp =
                    fertilizer * fertilizerRate;

                const pesticidesExp =
                    pesticides * pesticidesRate;

                const tractorExp =
                    tractorHour * tractorRate;

                const agroToolsExp =
                    agroTools * agroToolsRate;

                const total =
                    waterExp +
                    fertilizerExp +
                    pesticidesExp +
                    tractorExp +
                    agroToolsExp;

                console.log("Expense Calculation:", {
                    waterExp,
                    fertilizerExp,
                    pesticidesExp,
                    tractorExp,
                    agroToolsExp,
                    total
                });

                // =====================================================
                // 9. FARM NAME
                // =====================================================

                const farmName =
                    farm?.farmName ??
                    farm?.name ??
                    farm?.farm_name ??
                    "-";

                // =====================================================
                // 10. CREATE FINAL REPORT
                // =====================================================

                const finalReport = {
                    cropId: cid,

                    cropName:
                        crop.cropName ??
                        ai.cropName ??
                        "-",

                    farmName,

                    soil:
                        crop.soil ??
                        crop.soilType ??
                        ai.soil ??
                        ai.soilType ??
                        "-",

                    cropArea:
                        crop.cropArea ??
                        ai.cropArea ??
                        "-",

                    sownMonthYear:
                        crop.sownMonthYear ??
                        ai.sownMonthYear ??
                        "-",

                    harvestMonthYear:
                        crop.harvestMonthYear ??
                        ai.harvestMonthYear ??
                        "-",

                    yield:
                        crop.yield ??
                        ai.yield ??
                        "-",

                    // Quantities
                    water,
                    fertilizer,
                    pesticides,
                    tractorHour,
                    agroTools,

                    // Saved rates
                    waterRate,
                    fertilizerRate,
                    pesticidesRate,
                    tractorRate,
                    agroToolsRate,

                    // Calculated expenses
                    waterExp,
                    fertilizerExp,
                    pesticidesExp,
                    tractorExp,
                    agroToolsExp,

                    total
                };

                console.log(
                    "FINAL EXPENSE REPORT:",
                    finalReport
                );

                setReport(finalReport);

            } catch (err) {
                console.error(
                    "Expense Report Error:",
                    err
                );

                if (err.response) {
                    console.error(
                        "HTTP Status:",
                        err.response.status
                    );

                    console.error(
                        "Server Response:",
                        err.response.data
                    );
                }

                setError(
                    err.message ||
                    "Unable to load expense report."
                );

            } finally {
                setLoading(false);
            }
        };

        loadExpenseReport();

    }, [cid]);

    const handleBack = () => {
        navigate("/crop-list");
    };

    const handleLogout = () => {
        logoutUser().then(() => {
            localStorage.clear();
            sessionStorage.clear();
            navigate("/");
        });
    };

    // Shared navbar so every state (loading/error/success) matches the theme
    const TopNav = () => (
        <Navbar className="dashboard-nav" expand="lg">
            <Container fluid className="px-lg-5">
                <Navbar.Brand className="nav-brand" style={{ cursor: "pointer" }} onClick={() => navigate("/farmer-menu")}>
                    <i className="bi bi-flower3 nn-grow"></i>
                    <span>FarmVerse Workspace</span>
                </Navbar.Brand>
                <Navbar.Toggle aria-controls="ag-navbar-nav" className="border-0" />
                <Navbar.Collapse id="ag-navbar-nav">
                    <Nav className="ms-auto align-items-center gap-2">
                        <NavDropdown
                            title={<span className="fw-bold"><i className="bi bi-grid-1x2-fill me-1"></i> Operations</span>}
                            id="farm-dropdown"
                            align="end"
                            className="btn-nav-action"
                        >
                            <NavDropdown.Item onClick={() => navigate("/farm-add")}>
                                <i className="bi bi-plus-circle-fill" style={{ color: "#2E7D32" }}></i> Farm Entry
                            </NavDropdown.Item>
                            <NavDropdown.Item onClick={() => navigate("/farm-list")}>
                                <i className="bi bi-card-list" style={{ color: "#0369A1" }}></i> Farm Directory
                            </NavDropdown.Item>
                            <NavDropdown.Divider />
                            <NavDropdown.Item onClick={() => navigate("/crop-add")}>
                                <i className="bi bi-flower2" style={{ color: "#7CB342" }}></i> Crop Entry
                            </NavDropdown.Item>
                            <NavDropdown.Item onClick={() => navigate("/crop-list")}>
                                <i className="bi bi-pie-chart-fill" style={{ color: "#B45309" }}></i> Crop List &amp; Reports
                            </NavDropdown.Item>
                        </NavDropdown>
                        <button className="btn-nav-action logout-btn ms-lg-2" onClick={handleLogout}>
                            <i className="bi bi-box-arrow-right me-1"></i> Logout
                        </button>
                    </Nav>
                </Navbar.Collapse>
            </Container>
        </Navbar>
    );

    // =========================================================
    // LOADING
    // =========================================================

    if (loading) {
        return (
            <div className="nn-scene">
                <span className="nn-cloud c1" />
                <span className="nn-cloud c2" />
                <span className="nn-grass" />
                <TopNav />
                <Container className="dashboard-container py-5 text-center">
                    <div className="form-panel-card p-5 shadow-lg border-0 mx-auto" style={{ borderRadius: "28px", maxWidth: "560px" }}>
                        <div className="nn-tile green mx-auto mb-3" style={{ width: "80px", height: "80px", fontSize: "2.5rem" }}>
                            <FaMoneyBillWave />
                        </div>
                        <h3 className="fw-bold text-dark mb-2">Calculating Expense Report...</h3>
                        <p className="text-muted small mb-4">
                            Fetching crop data, predicted resource needs, and saved rates for Crop #{cid}.
                        </p>
                        <div className="spinner-border text-success" role="status">
                            <span className="visually-hidden">Loading...</span>
                        </div>
                    </div>
                </Container>
            </div>
        );
    }

    // =========================================================
    // ERROR
    // =========================================================

    if (error) {
        return (
            <div className="nn-scene">
                <span className="nn-cloud c1" />
                <span className="nn-cloud c2" />
                <span className="nn-grass" />
                <TopNav />
                <Container className="dashboard-container py-5 text-center">
                    <div className="form-panel-card p-5 shadow-lg border-0 mx-auto" style={{ borderRadius: "28px", maxWidth: "560px" }}>
                        <div className="nn-tile amber mx-auto mb-3" style={{ width: "70px", height: "70px", fontSize: "2rem" }}>
                            ❌
                        </div>
                        <h3 className="fw-bold text-dark mb-2">Expense Report Failed</h3>
                        <p className="text-danger fw-bold mb-4">{error}</p>
                        <button
                            className="btn-primary-ag px-4 py-2.5 fw-bold d-inline-flex align-items-center gap-2"
                            style={{ borderRadius: "12px" }}
                            onClick={handleBack}
                        >
                            <FaArrowLeft /> Return to Crop List
                        </button>
                    </div>
                </Container>
            </div>
        );
    }

    // =========================================================
    // NO REPORT
    // =========================================================

    if (!report) {
        return (
            <div className="nn-scene">
                <span className="nn-cloud c1" />
                <span className="nn-cloud c2" />
                <span className="nn-grass" />
                <TopNav />
                <Container className="dashboard-container py-5 text-center">
                    <div className="form-panel-card p-5 shadow-lg border-0 mx-auto" style={{ borderRadius: "28px", maxWidth: "560px" }}>
                        <div className="nn-tile green mx-auto mb-3" style={{ width: "70px", height: "70px", fontSize: "2rem" }}>
                            🌿
                        </div>
                        <h3 className="fw-bold text-dark mb-2">No Expense Data</h3>
                        <p className="text-muted small mb-4">No expense data available for Crop #{cid}.</p>
                        <button
                            className="btn-primary-ag px-4 py-2.5 fw-bold d-inline-flex align-items-center gap-2"
                            style={{ borderRadius: "12px" }}
                            onClick={handleBack}
                        >
                            <FaArrowLeft /> Return to Crop List
                        </button>
                    </div>
                </Container>
            </div>
        );
    }

    // =========================================================
    // DISPLAY REPORT
    // =========================================================

    return (
        <div className="nn-scene">
            <span className="nn-cloud c1" />
            <span className="nn-cloud c2" />
            <span className="nn-cloud c3" />
            <span className="nn-grass" />

            <TopNav />

            <Container className="dashboard-container py-4">
                {/* Breadcrumb */}
                <div className="d-flex align-items-center justify-content-between mb-4 flex-wrap gap-2">
                    <button
                        className="btn btn-outline-secondary btn-sm fw-bold px-3 py-2 d-inline-flex align-items-center gap-2"
                        style={{ borderRadius: "12px", background: "rgba(255,255,255,0.85)" }}
                        onClick={handleBack}
                    >
                        <FaArrowLeft /> Back to Crops
                    </button>

                    <span className="badge-ag-amber">
                        💰 AI-Assisted Expense Analysis
                    </span>
                </div>

                {/* Top Banner */}
                <div className="form-panel-card p-4 p-md-5 overflow-hidden shadow-lg border-0 mb-4" style={{ borderRadius: "28px" }}>
                    <div className="d-flex align-items-center gap-4 flex-wrap">
                        <div className="nn-tile green nn-float" style={{ width: "76px", height: "76px", fontSize: "2.4rem" }}>
                            <FaMoneyBillWave />
                        </div>
                        <div>
                            <span className="badge bg-success bg-opacity-20 text-success px-3 py-1 fw-bold mb-2" style={{ borderRadius: "8px" }}>
                                Crop ID: #{report.cropId}
                            </span>
                            <h1 className="display-6 fw-bold mb-1 text-dark">
                                {report.cropName} Expense Report
                            </h1>
                            <p className="text-muted mb-0">
                                Detailed resource requirements and expense calculation
                            </p>
                        </div>
                    </div>
                </div>

                <Row className="g-4">
                    {/* Crop Details */}
                    <Col lg={5}>
                        <div className="form-panel-card p-4 h-100 shadow-lg border-0" style={{ borderRadius: "28px" }}>
                            <div className="form-section-header">
                                <div className="nn-tile lime">
                                    <FaLeaf />
                                </div>
                                <div>
                                    <h3 className="fw-bold mb-0 text-dark" style={{ fontSize: "1.3rem" }}>
                                        Crop Details
                                    </h3>
                                    <small className="text-muted">Specifications and cycle timeline</small>
                                </div>
                            </div>

                            <div className="info-grid">
                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaSeedling className="text-success" /> Crop Name
                                    </span>
                                    <span className="detail-info-value">{report.cropName}</span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaVectorSquare className="text-success" /> Farm Name
                                    </span>
                                    <span className="detail-info-value">{report.farmName}</span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaGlobeAmericas className="text-success" /> Soil Type
                                    </span>
                                    <span className="detail-info-value badge bg-success bg-opacity-10 text-success px-3 py-1">
                                        {report.soil}
                                    </span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaVectorSquare className="text-success" /> Crop Area
                                    </span>
                                    <span className="detail-info-value">{report.cropArea} Acres</span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaCalendarAlt className="text-success" /> Sown Month / Year
                                    </span>
                                    <span className="detail-info-value">{report.sownMonthYear}</span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaCalendarAlt className="text-success" /> Harvest Month / Year
                                    </span>
                                    <span className="detail-info-value">{report.harvestMonthYear}</span>
                                </div>

                                <div className="detail-info-row">
                                    <span className="detail-info-label">
                                        <FaChartLine className="text-success" /> Expected Yield
                                    </span>
                                    <span className="detail-info-value text-success fw-bold">{report.yield}</span>
                                </div>
                            </div>
                        </div>
                    </Col>

                    {/* Resource & Cost Table */}
                    <Col lg={7}>
                        <div className="form-panel-card p-4 h-100 shadow-lg border-0" style={{ borderRadius: "28px" }}>
                            <div className="form-section-header">
                                <div className="nn-tile sky">
                                    <FaTractor />
                                </div>
                                <div>
                                    <h3 className="fw-bold mb-0 text-dark" style={{ fontSize: "1.3rem" }}>
                                        Resource Requirements &amp; Cost Analysis
                                    </h3>
                                    <small className="text-muted">Required quantity × saved rate per unit</small>
                                </div>
                            </div>

                            <div className="table-responsive">
                                <table className="table table-hover align-middle mb-0">
                                    <thead>
                                        <tr>
                                            <th>Resource</th>
                                            <th>Required Quantity</th>
                                            <th className="text-end">Total Expense</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><FaWater className="text-primary me-2" />Water</td>
                                            <td>{report.water} Gallons</td>
                                            <td className="text-end fw-bold">₹ {report.waterExp.toFixed(2)}</td>
                                        </tr>
                                        <tr>
                                            <td><FaFlask className="text-success me-2" />Fertilizer</td>
                                            <td>{report.fertilizer} kg</td>
                                            <td className="text-end fw-bold">₹ {report.fertilizerExp.toFixed(2)}</td>
                                        </tr>
                                        <tr>
                                            <td><FaShieldAlt className="text-warning me-2" />Pesticides</td>
                                            <td>{report.pesticides} kg</td>
                                            <td className="text-end fw-bold">₹ {report.pesticidesExp.toFixed(2)}</td>
                                        </tr>
                                        <tr>
                                            <td><FaTractor className="text-dark me-2" />Tractor Usage</td>
                                            <td>{report.tractorHour} Hours</td>
                                            <td className="text-end fw-bold">₹ {report.tractorExp.toFixed(2)}</td>
                                        </tr>
                                        <tr>
                                            <td><FaTools className="text-secondary me-2" />Agro Tools</td>
                                            <td>{report.agroTools} Units</td>
                                            <td className="text-end fw-bold">₹ {report.agroToolsExp.toFixed(2)}</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>

                            <div
                                className="mt-4 p-4 text-center fw-bold"
                                style={{
                                    borderRadius: "16px",
                                    background: "rgba(46, 125, 50, 0.10)",
                                    color: "var(--nn-primary)",
                                    fontSize: "1.4rem"
                                }}
                            >
                                💰 Total Crop Expense: ₹ {report.total.toFixed(2)}
                            </div>

                            <div className="mt-4 pt-3 border-top d-flex gap-3 flex-wrap">
                                <button
                                    className="btn-nav-action flex-grow-1 py-3 fw-bold d-inline-flex align-items-center justify-content-center gap-2"
                                    style={{ borderRadius: "14px" }}
                                    onClick={handleBack}
                                >
                                    <FaArrowLeft /> Return to Crop List
                                </button>
                            </div>
                        </div>
                    </Col>
                </Row>
            </Container>
        </div>
    );
};

export default FarmCropExpense;
